import { useMemo, useState } from "react";
import { setParentKey } from "../lib/github";
import { MOODS } from "../data/moods";

const emptyQuestion=()=>({text:"",options:["","","",""],correctIndex:0,hint:""});

export default function ParentPanel({ profile, onUpdateProfile, onUploadTest }) {
  const [unlocked,setUnlocked]=useState(false);
  if(!unlocked)return <LoginGate onUnlock={()=>setUnlocked(true)}/>;
  return <div className="app-shell space-y-4 pb-5"><section className="glass-card p-5"><p className="text-[9px] font-black uppercase tracking-[.2em] text-[#52E3C2]">Yönetim Alanı</p><h2 className="font-display mt-1 text-xl font-black">Ebeveyn Paneli</h2><p className="mt-2 text-xs leading-relaxed text-[#8793B4]">Görev ekle, ilerlemeyi takip et ve gerçek yaşam ödüllerini yönet.</p></section><Analysis profile={profile}/><TestBuilder onUpload={onUploadTest}/><RewardsManager profile={profile} onUpdateProfile={onUpdateProfile}/><MoodHistory profile={profile}/></div>;
}

function LoginGate({onUnlock}) {
  const [key,setKey]=useState(''),[error,setError]=useState(''),[loading,setLoading]=useState(false);
  async function submit(e){e.preventDefault();setLoading(true);setError('');setParentKey(key);try{const res=await fetch('/api/verify-parent',{method:'POST',headers:{'x-parent-key':key}});const data=await res.json();if(data.ok)onUnlock();else setError('Ebeveyn anahtarı doğrulanamadı.');}catch{setError('Sunucuya ulaşılamadı. Çevrimdışı modda bu alan doğrulanamıyor.');}finally{setLoading(false);}}
  return <div className="app-shell py-8"><form onSubmit={submit} className="glass-card mx-auto max-w-md p-5"><div className="flex h-12 w-12 items-center justify-center rounded-2xl bg-[#A98CFF]/10 text-[#A98CFF]"><LockIcon/></div><p className="mt-4 text-[9px] font-black uppercase tracking-[.2em] text-[#A98CFF]">Korunan Alan</p><h2 className="font-display mt-1 text-xl font-black">Ebeveyn Paneli</h2><p className="mt-2 text-xs leading-relaxed text-[#8793B4]">Bu alan görev oluşturma ve ödül yönetimi içerir. Ebeveyn erişim anahtarını gir.</p><input type="password" value={key} onChange={(e)=>setKey(e.target.value)} placeholder="Ebeveyn anahtarı" className="game-input mt-5"/>{error&&<p className="mt-2 text-xs font-bold text-[#FF789E]">{error}</p>}<button disabled={loading} className="sticker-btn mt-4 w-full py-3 text-sm">{loading?'Kontrol ediliyor...':'Giriş Yap →'}</button></form></div>;
}

function Analysis({profile}) {
  const data=useMemo(()=>{const out={};(profile.history||[]).forEach((h)=>{out[h.subject] ||= {correct:0,total:0,count:0};out[h.subject].correct+=h.correctCount;out[h.subject].total+=h.totalCount;out[h.subject].count+=1;});return out;},[profile.history]);
  const totalTests=(profile.history||[]).length; const activeMistakes=(profile.mistakeBox||[]).filter((m)=>!m.resolved).length;
  return <section className="glass-card p-4"><div className="flex items-center justify-between"><div><p className="text-[9px] font-black uppercase tracking-[.18em] text-[#70D6FF]">İlerleme</p><h3 className="mt-1 text-sm font-black">Ders Bazlı Analiz</h3></div><span className="game-chip">{totalTests} test</span></div><div className="mt-4 grid grid-cols-2 gap-2"><Metric value={profile.xp||0} label="Toplam XP" color="#52E3FF"/><Metric value={activeMistakes} label="Bekleyen Tekrar" color="#FF789E"/></div><div className="mt-4 space-y-3">{Object.keys(data).length===0&&<p className="text-xs text-[#687494]">Henüz test sonucu yok.</p>}{Object.entries(data).map(([subject,s])=>{const pct=s.total?Math.round(s.correct/s.total*100):0;return <div key={subject}><div className="mb-1.5 flex justify-between text-[10px]"><span className="font-black">{subject}</span><span className="text-[#8793B4]">{pct}% · {s.count} test</span></div><div className="h-2 overflow-hidden rounded-full bg-white/[.06]"><div className="h-full rounded-full" style={{width:`${pct}%`,background:pct>=80?'linear-gradient(90deg,#52E3C2,#52E3FF)':pct>=50?'linear-gradient(90deg,#FFD166,#A98CFF)':'linear-gradient(90deg,#FF789E,#A98CFF)'}}/></div></div>})}</div></section>;
}

function TestBuilder({onUpload}) {
  const [subject,setSubject]=useState('Matematik'),[title,setTitle]=useState(''),[week,setWeek]=useState(1),[gradeLevel,setGradeLevel]=useState('4. Sınıf'),[targetSeconds,setTargetSeconds]=useState(40),[hintsAllowed,setHintsAllowed]=useState(2),[questions,setQuestions]=useState([emptyQuestion()]),[status,setStatus]=useState('');
  function patch(i,p){setQuestions((qs)=>qs.map((q,idx)=>idx===i?{...q,...p}:q));} function option(i,oi,v){setQuestions((qs)=>qs.map((q,idx)=>idx===i?{...q,options:q.options.map((o,j)=>j===oi?v:o)}:q));}
  async function submit(){if(!title.trim()||questions.some((q)=>!q.text.trim()||q.options.some((o)=>!o.trim()))){setStatus('Başlık ve tüm soru/şık alanları doldurulmalı.');return;}const id=`${subject.toLowerCase().replace(/\s/g,'-')}-hafta${week}-${Date.now().toString().slice(-5)}`;const test={id,subject,title,week:Number(week),gradeLevel,targetSecondsPerQuestion:Number(targetSeconds)||null,hintsAllowed:Number(hintsAllowed)||0,questions:questions.map((q,i)=>({...q,id:`q${i+1}`}))};setStatus('Yayınlanıyor...');try{await onUpload(test);setStatus('Görev yayınlandı.');setTitle('');setQuestions([emptyQuestion()]);}catch{setStatus('Görev yayınlanamadı.');}}
  return <section className="glass-card p-4"><div><p className="text-[9px] font-black uppercase tracking-[.18em] text-[#A98CFF]">İçerik</p><h3 className="mt-1 text-sm font-black">Yeni Görev Oluştur</h3></div><div className="mt-4 grid grid-cols-2 gap-2"><label className="text-[10px] font-bold text-[#9AA7C7]">Ders<select value={subject} onChange={(e)=>setSubject(e.target.value)} className="game-input mt-1"><option>Matematik</option><option>Türkçe</option><option>Fen Bilimleri</option><option>Sosyal Bilgiler</option><option>İngilizce</option></select></label><label className="text-[10px] font-bold text-[#9AA7C7]">Hafta<input type="number" value={week} onChange={(e)=>setWeek(e.target.value)} className="game-input mt-1"/></label></div><label className="mt-2 block text-[10px] font-bold text-[#9AA7C7]">Görev başlığı<input value={title} onChange={(e)=>setTitle(e.target.value)} className="game-input mt-1" placeholder="Örn. Kesirler Keşif Görevi"/></label><div className="mt-2 grid grid-cols-3 gap-2"><label className="text-[10px] font-bold text-[#9AA7C7]">Sınıf<input value={gradeLevel} onChange={(e)=>setGradeLevel(e.target.value)} className="game-input mt-1"/></label><label className="text-[10px] font-bold text-[#9AA7C7]">Hedef sn<input type="number" value={targetSeconds} onChange={(e)=>setTargetSeconds(e.target.value)} className="game-input mt-1"/></label><label className="text-[10px] font-bold text-[#9AA7C7]">İpucu<input type="number" value={hintsAllowed} onChange={(e)=>setHintsAllowed(e.target.value)} className="game-input mt-1"/></label></div><div className="mt-4 space-y-3">{questions.map((q,i)=><div key={i} className="rounded-2xl border border-white/[.07] bg-white/[.025] p-3"><div className="flex items-center justify-between"><p className="text-xs font-black">Soru {i+1}</p>{questions.length>1&&<button onClick={()=>setQuestions((qs)=>qs.filter((_,j)=>j!==i))} className="text-[10px] font-bold text-[#FF789E]">Sil</button>}</div><input value={q.text} onChange={(e)=>patch(i,{text:e.target.value})} placeholder="Soru metni" className="game-input mt-2 text-xs"/>{q.options.map((o,oi)=><div key={oi} className="mt-2 flex items-center gap-2"><input type="radio" checked={q.correctIndex===oi} onChange={()=>patch(i,{correctIndex:oi})}/><input value={o} onChange={(e)=>option(i,oi,e.target.value)} placeholder={`Şık ${String.fromCharCode(65+oi)}`} className="game-input text-xs"/></div>)}<input value={q.hint} onChange={(e)=>patch(i,{hint:e.target.value})} placeholder="İpucu (isteğe bağlı)" className="game-input mt-2 text-xs"/></div>)}</div><button onClick={()=>setQuestions((q)=>[...q,emptyQuestion()])} className="mt-3 text-xs font-black text-[#A98CFF]">+ Soru ekle</button>{status&&<p className="mt-2 text-xs text-[#9AA7C7]">{status}</p>}<button onClick={submit} className="sticker-btn mt-4 w-full py-3 text-xs">Görevi Yayınla →</button></section>;
}

function RewardsManager({profile,onUpdateProfile}) { const [label,setLabel]=useState(''),[cost,setCost]=useState(100);function add(){if(!label.trim())return;onUpdateProfile({...profile,rewardsCatalog:[...(profile.rewardsCatalog||[]),{id:`r${Date.now()}`,label,cost:Number(cost)}]});setLabel('');}function remove(id){onUpdateProfile({...profile,rewardsCatalog:profile.rewardsCatalog.filter((r)=>r.id!==id)});}function fulfil(id){onUpdateProfile({...profile,redemptions:profile.redemptions.map((r)=>r.id===id?{...r,fulfilled:true}:r)});}const pending=(profile.redemptions||[]).filter((r)=>!r.fulfilled);return <section className="glass-card p-4"><p className="text-[9px] font-black uppercase tracking-[.18em] text-[#FFD166]">Gerçek Yaşam Ödülleri</p><h3 className="mt-1 text-sm font-black">Ödül Kataloğu</h3><div className="mt-3 flex gap-2"><input value={label} onChange={(e)=>setLabel(e.target.value)} placeholder="Örn. Film seçimi" className="game-input flex-1 text-xs"/><input type="number" value={cost} onChange={(e)=>setCost(e.target.value)} className="game-input w-20 text-xs"/><button onClick={add} className="sticker-btn px-3 text-xs">Ekle</button></div><div className="mt-3 space-y-2">{(profile.rewardsCatalog||[]).map((r)=><div key={r.id} className="flex items-center gap-2 rounded-xl border border-white/[.06] bg-white/[.025] p-2.5"><p className="flex-1 text-[11px] font-bold">{r.label}</p><span className="text-[10px] text-[#FFD166]">◈ {r.cost}</span><button onClick={()=>remove(r.id)} className="text-[9px] text-[#FF789E]">Kaldır</button></div>)}</div>{pending.length>0&&<div className="mt-4 border-t border-white/[.07] pt-3"><p className="text-xs font-black">Bekleyen talepler</p>{pending.map((r)=><div key={r.id} className="mt-2 flex items-center gap-2"><span className="flex-1 text-[11px]">{r.label}</span><button onClick={()=>fulfil(r.id)} className="game-chip text-[#52E3C2]">Teslim edildi ✓</button></div>)}</div>}</section>;}
function MoodHistory({profile}) {const rows=[...(profile.moodLog||[])].slice(-14).reverse();return <section className="glass-card p-4"><p className="text-[9px] font-black uppercase tracking-[.18em] text-[#70D6FF]">Günlük Kayıt</p><h3 className="mt-1 text-sm font-black">Son Duygu Durumları</h3><p className="mt-1 text-[10px] text-[#8793B4]">Çocuğun kendi seçtiği günlük durum; konuşmaya başlamak için küçük bir ipucu olabilir.</p><div className="mt-3 flex flex-wrap gap-2">{rows.length===0?<p className="text-xs text-[#687494]">Henüz kayıt yok.</p>:rows.map((e)=>{const m=MOODS.find((x)=>x.id===e.mood);return <div key={e.date} className="rounded-xl border border-white/[.07] bg-white/[.03] px-2.5 py-2 text-center"><span className="text-lg">{m?.emoji}</span><span className="mt-1 block text-[8px] text-[#8793B4]">{e.date.slice(5)}</span></div>})}</div></section>;}
function Metric({value,label,color}){return <div className="rounded-2xl border border-white/[.06] bg-white/[.025] p-3"><p className="font-display text-xl font-black" style={{color}}>{value}</p><p className="mt-1 text-[8px] font-black uppercase tracking-[.13em] text-[#687494]">{label}</p></div>}
function LockIcon(){return <svg viewBox="0 0 24 24" className="h-5 w-5" fill="none" stroke="currentColor" strokeWidth="1.9"><rect x="5" y="10" width="14" height="10" rx="3"/><path d="M8 10V7a4 4 0 0 1 8 0v3"/></svg>}
