import fs from "node:fs";
const read=(p)=>fs.readFileSync(new URL(`../${p}`,import.meta.url),"utf8");
const must=(ok,msg)=>{if(!ok){console.error(`❌ ${msg}`);process.exitCode=1}else console.log(`✅ ${msg}`)};
const main=read("src/main.jsx"),app=read("src/V47App.jsx"),shell=read("src/components/shell/AppShell.jsx"),hero=read("src/components/v47/HeroHub.jsx"),lessons=read("src/components/v47/LessonsHub.jsx"),assets=read("src/data/gameAssets.js"),css=read("src/v47-reference.css");
must(main.includes("V47App")&&main.includes("v47-reference.css"),"Production entrypoint yalnızca V4.7 referans uygulamasına bağlı");
must(!main.includes("v46-layered-rig")&&!main.includes("./App.jsx"),"Eski V4.6 layered rig production girişinden çıkarıldı");
must(hero.includes("CHARACTER_PRESETS")&&hero.includes("PRESET_LABELS")&&hero.includes("heroMaster"),"Premium master + tam-render kombinasyon presetleri aktif");
must(assets.includes("explorer:")&&assets.includes("galaxy:")&&assets.includes("cloud:")&&assets.includes("forest:"),"Keşif/Galaksi/Bulut/Orman tam karakter presetleri mevcut");
must(shell.includes("lessons")&&app.includes("lessons"),"Dersler ana navigasyona bağlı");
must(shell.includes("pets")&&shell.includes("base")&&shell.includes("leaderboard"),"Dost/Üs/Liderlik referans navigasyonunda bağlı");
must(lessons.includes("onStartTest")&&lessons.includes("onGeneratePractice"),"Ders kartları gerçek test/pratik akışını başlatıyor");
must(css.includes(".v47-hero-page")&&css.includes(".v47-lessons-page")&&css.includes(".v47-topbar"),"Referans görsel tasarım sistemi yüklü");
must(app.includes("TestSolver")&&app.includes("ResultScreen"),"Ders → soru → sonuç bağlantısı korunuyor");
if(process.exitCode)process.exit(process.exitCode);
console.log("🚀 V4.7 — FULL REFERENCE REDESIGN / PREMIUM HERO / CONNECTED LESSONS doğrulaması başarılı.");
