import { useMemo, useState } from "react";
import { ITEMS, SETS, SET_LOADOUTS, makeAvatarForSet } from "../../data/avatarParts";
import { getCatalogMeta } from "../../data/catalog";
import { CHARACTER_PRESETS, getCharacterSetAsset } from "../../data/gameAssets";
import { playPop } from "../../lib/sound";

const SLOT_TABS=[["outfit","Kıyafet","👕"],["shoes","Ayakkabı","👢"],["headwear","Başlık","🧢"],["face","Aksesuar","◉"],["back","Sırt","🎒"]];
const MOTIONS=[["idle","Rahat","🏃"],["thinking","Düşün","🤔"],["happy","Mutlu","🙂"],["victory","Zafer","🏆"]];
const SET_ORDER=["explorer","cloud","forest"];
function inferSet(profile){if(SETS[profile.avatar?.set])return profile.avatar.set;const outfit=ITEMS.find((item)=>item.id===profile.avatar?.outfit);return outfit?.set||"explorer";}
function fallbackFor(setId){return CHARACTER_PRESETS[setId]||CHARACTER_PRESETS.explorer||"";}
function SafeImage({src,fallback,alt,className}){return <img className={className} src={src||fallback} alt={alt||""} onError={(e)=>{if(fallback&&e.currentTarget.src!==fallback){e.currentTarget.onerror=null;e.currentTarget.src=fallback;}}}/>;}
function SetImage({setId,alt,className}){return <SafeImage src={getCharacterSetAsset(setId)} fallback={fallbackFor(setId)} alt={alt} className={className}/>;}
function ItemPreview({item,variant="card"}){return <span className={`v49-preview-window is-${variant} slot-${item.slot}`}><SetImage setId={item.set} alt={item.label}/></span>;}

export default function HeroHub({profile,onChangeAvatar,onOpenLessons,onOpenShop}){
 const[slot,setSlot]=useState("outfit");const[motion,setMotion]=useState("idle");const activeSet=inferSet(profile);const[previewSet,setPreviewSet]=useState(activeSet);const[selectedId,setSelectedId]=useState(profile.avatar?.outfit||SET_LOADOUTS.explorer.outfit);
 const owned=useMemo(()=>new Set(profile.unlockedItems||[]),[profile.unlockedItems]);const items=useMemo(()=>ITEMS.filter((item)=>item.slot===slot).map(getCatalogMeta),[slot]);const selected=items.find((i)=>i.id===selectedId)||items.find((i)=>i.set===previewSet)||items[0];const activeLoadout=SET_LOADOUTS[activeSet];const equipped=Object.values(activeLoadout).map((id)=>ITEMS.find((item)=>item.id===id)).filter(Boolean).map(getCatalogMeta);const setOwned=(setId)=>Object.values(SET_LOADOUTS[setId]||{}).every((id)=>owned.has(id));const isTrying=previewSet!==activeSet;
 function applySet(setId){if(!SETS[setId]||!setOwned(setId))return;playPop();onChangeAvatar?.(makeAvatarForSet(setId,profile.avatar));setPreviewSet(setId);}
 function previewItem(item){setSelectedId(item.id);setPreviewSet(item.set);playPop();}
 function actionSelected(){if(!selected)return;if(setOwned(selected.set)){applySet(selected.set);return;}onOpenShop?.();}
 function randomize(){const available=SET_ORDER.filter(setOwned);const setId=available[Math.floor(Math.random()*available.length)]||"explorer";setPreviewSet(setId);setSelectedId(SET_LOADOUTS[setId]?.[slot]||SET_LOADOUTS[setId]?.outfit);playPop();}
 return <section className="v47-hero-page">
  <aside className="v47-equipped-panel v47-panel"><h3>Kuşanılanlar</h3><div className="v47-equipped-list">{equipped.map((item)=><button key={item.id} onClick={()=>{setSlot(item.slot);setSelectedId(item.id);setPreviewSet(activeSet);}}><ItemPreview item={item} variant="equipped"/><span><small>{item.slotMeta.label}</small><strong>{item.label}</strong></span></button>)}</div></aside>
  <div className="v47-stage-panel"><div className="v47-scene-glow"/>{isTrying&&<div className="v494-tryon-badge">DENEME · {SETS[previewSet]?.shortLabel}</div>}<div className={`v47-full-hero motion-${motion}`}><SetImage className="v49-set-hero" setId={previewSet} alt={`${SETS[previewSet]?.label} Bilgin Kaşif`}/></div><div className="v47-motion-stack">{MOTIONS.map(([id,label,icon])=><button key={id} className={motion===id?"is-active":""} onClick={()=>{setMotion(id);playPop();}}><span>{icon}</span><b>{label}</b></button>)}<button onClick={randomize}><span>🎲</span><b>Rastgele</b></button></div></div>
  <div className="v47-wardrobe-panel v47-panel"><div className="v47-slot-tabs">{SLOT_TABS.map(([id,label,icon])=><button key={id} className={slot===id?"is-active":""} onClick={()=>{setSlot(id);setSelectedId(SET_LOADOUTS[previewSet]?.[id]||ITEMS.find((x)=>x.slot===id)?.id);playPop();}}><span>{icon}</span>{label}</button>)}</div><div className="v47-shop-head"><h2>Gardırop · {SLOT_TABS.find(([id])=>id===slot)?.[1]}</h2><b>{items.filter((item)=>setOwned(item.set)).length} / {items.length}</b></div><div className="v47-shop-grid">{items.map((item)=>{const isOn=activeLoadout?.[slot]===item.id;const isPreview=previewSet===item.set;const unlocked=setOwned(item.set);const set=SETS[item.set];return <button key={item.id} className={`v47-shop-card rarity-${item.rarity} ${isOn?"is-equipped":""} ${isPreview?"is-previewing":""} ${!unlocked?"is-locked":""}`} onClick={()=>previewItem(item)}>{isOn&&<i>✓</i>}<ItemPreview item={item}/><strong>{item.label}</strong><small style={{color:item.rarityMeta.color}}>{isPreview&&!isOn?"👁 DENENİYOR":unlocked?set.label:"🔒 DENE · DÜKKANDA AÇ"}</small></button>;})}</div>
  {selected&&<div className="v47-detail-card"><div><span>{SETS[selected.set]?.label}</span><h3>{selected.label}</h3><p>{SETS[selected.set]?.description}</p><ul><li>✦ {SETS[selected.set]?.bonus}</li><li>👁 Seçince karakter üzerinde anında denenir</li><li>⬡ Set bütünlüğü: 5 parça birlikte uygulanır</li></ul></div><ItemPreview item={selected} variant="detail"/><button className={activeSet===selected.set?"is-on":""} onClick={actionSelected}>{activeSet===selected.set?"✓ TAKILI":setOwned(selected.set)?"BU SETİ KUŞAN":"DÜKKANDA AÇ →"}</button></div>}
  <div className="v47-combos"><h3>Tam Setler · tıklayarak dene</h3><div>{SET_ORDER.map((setId)=>{const active=activeSet===setId;const preview=previewSet===setId;const complete=setOwned(setId);return <button key={setId} className={`${active?"is-active":""} ${preview?"is-previewing":""} ${!complete?"is-locked":""}`} onClick={()=>{setPreviewSet(setId);setSelectedId(SET_LOADOUTS[setId]?.[slot]||SET_LOADOUTS[setId]?.outfit);playPop();}}><SetImage className="v49-combo-render" setId={setId} alt={`${SETS[setId].label} önizleme`}/><span>{SETS[setId].shortLabel}</span>{active?<i>✓</i>:preview?<i>👁</i>:<i>{complete?"★":"🔒"}</i>}</button>;})}</div></div></div>
  <div className="v47-learning-strip"><div className="v47-lesson-cta"><span>📖</span><div><strong>Dersler & Öğrenme</strong><small>Yeni bilgiler keşfet, sınavları geç, ödüller kazan.</small></div><button onClick={onOpenLessons}>Derslere Git →</button></div><div className="v47-daily-mini"><b>Önerilen Ders</b><span>Fen Bilimleri · Keşif Görevi</span><i><em style={{width:"60%"}}/></i></div><div className="v47-daily-mini"><b>Günlük Hedef</b><span>1 ders tamamla · 1 soru çöz</span><i><em style={{width:"34%"}}/></i></div></div>
 </section>;
}
