import { useMemo, useState } from "react";
import { ITEMS, SETS, SET_LOADOUTS, makeAvatarForSet } from "../../data/avatarParts";
import { getCatalogMeta } from "../../data/catalog";
import { getCharacterSetAsset } from "../../data/gameAssets";
import { playPop } from "../../lib/sound";
const SLOT_TABS=[["outfit","Kıyafet","👕"],["shoes","Ayakkabı","👢"],["headwear","Başlık","🧢"],["face","Aksesuar","◉"],["back","Sırt","🎒"]];
const MOTIONS=[["idle","Rahat","🏃"],["thinking","Düşün","🤔"],["happy","Mutlu","🙂"],["victory","Zafer","🏆"]];
const SET_ORDER=["explorer","cloud","forest"];
function inferSet(profile){if(SETS[profile.avatar?.set])return profile.avatar.set;const outfit=ITEMS.find((item)=>item.id===profile.avatar?.outfit);return outfit?.set||"explorer";}
export default function HeroHub({profile,onChangeAvatar,onOpenLessons,onBuyItem}){
 const[slot,setSlot]=useState("outfit");const[motion,setMotion]=useState("idle");const[selectedId,setSelectedId]=useState(profile.avatar?.outfit||SET_LOADOUTS.explorer.outfit);const owned=useMemo(()=>new Set(profile.unlockedItems||[]),[profile.unlockedItems]);const items=useMemo(()=>ITEMS.filter((item)=>item.slot===slot).map(getCatalogMeta),[slot]);const selected=items.find((i)=>i.id===selectedId)||items[0];const activeSet=inferSet(profile);const heroSrc=getCharacterSetAsset(activeSet);const activeLoadout=SET_LOADOUTS[activeSet];const equipped=Object.values(activeLoadout).map((id)=>ITEMS.find((item)=>item.id===id)).filter(Boolean).map(getCatalogMeta);const setOwned=(setId)=>Object.values(SET_LOADOUTS[setId]||{}).every((id)=>owned.has(id));
 function applySet(setId){if(!SETS[setId])return;const firstItem=ITEMS.find((item)=>item.set===setId);if(!setOwned(setId)){onBuyItem?.(firstItem);return;}playPop();onChangeAvatar?.(makeAvatarForSet(setId,profile.avatar));}
 function choose(item){setSelectedId(item.id);playPop();if(!setOwned(item.set)){onBuyItem?.(item);return;}onChangeAvatar?.(makeAvatarForSet(item.set,profile.avatar));}
 function randomize(){const available=SET_ORDER.filter(setOwned);const setId=available[Math.floor(Math.random()*available.length)]||"explorer";applySet(setId);}
 return <section className="v47-hero-page">
  <aside className="v47-equipped-panel v47-panel"><h3>Kuşanılanlar</h3><div className="v47-equipped-list">{equipped.map((item)=><button key={item.id} onClick={()=>{setSlot(item.slot);setSelectedId(item.id);}}><img className={`v49-item-preview slot-${item.slot}`} src={item.cardAsset} alt=""/><span><small>{item.slotMeta.label}</small><strong>{item.label}</strong></span></button>)}</div></aside>
  <div className="v47-stage-panel"><div className="v47-scene-glow"/><div className={`v47-full-hero motion-${motion}`}><img className="v49-set-hero" src={heroSrc} alt={`${SETS[activeSet].label} Bilgin Kaşif`}/></div><div className="v47-motion-stack">{MOTIONS.map(([id,label,icon])=><button key={id} className={motion===id?"is-active":""} onClick={()=>{setMotion(id);playPop();}}><span>{icon}</span><b>{label}</b></button>)}<button onClick={randomize}><span>🎲</span><b>Rastgele</b></button></div></div>
  <div className="v47-wardrobe-panel v47-panel"><div className="v47-slot-tabs">{SLOT_TABS.map(([id,label,icon])=><button key={id} className={slot===id?"is-active":""} onClick={()=>{setSlot(id);setSelectedId(SET_LOADOUTS[activeSet]?.[id]||ITEMS.find((x)=>x.slot===id)?.id);playPop();}}><span>{icon}</span>{label}</button>)}</div><div className="v47-shop-head"><h2>{SLOT_TABS.find(([id])=>id===slot)?.[1]}ler</h2><b>{items.filter((item)=>setOwned(item.set)).length} / {items.length}</b></div><div className="v47-shop-grid">{items.map((item)=>{const isOn=activeLoadout?.[slot]===item.id;const unlocked=setOwned(item.set);const set=SETS[item.set];return <button key={item.id} className={`v47-shop-card rarity-${item.rarity} ${isOn?"is-equipped":""}`} onClick={()=>choose(item)}>{isOn&&<i>✓</i>}<img className={`v49-item-preview slot-${item.slot}`} src={item.cardAsset} alt=""/><strong>{item.label}</strong><small style={{color:item.rarityMeta.color}}>{unlocked?set.label:`${set.setPrice} COIN · SET`}</small></button>;})}</div>
  {selected&&<div className="v47-detail-card"><div><span>{SETS[selected.set]?.label}</span><h3>{selected.label}</h3><p>{SETS[selected.set]?.description}</p><ul><li>✦ {SETS[selected.set]?.bonus}</li><li>◉ Bilgin Kaşif'e özel tam render</li><li>⬡ Set bütünlüğü: 5 parça birlikte uygulanır</li></ul></div><img className={`v49-detail-preview slot-${selected.slot}`} src={selected.cardAsset} alt=""/><button className={activeSet===selected.set?"is-on":""} onClick={()=>choose(selected)}>{activeSet===selected.set?"✓ TAKILI":setOwned(selected.set)?"SETİ KUŞAN":`${SETS[selected.set]?.setPrice||0} COIN · SETİ AÇ`}</button></div>}
  <div className="v47-combos"><h3>Tam Setler</h3><div>{SET_ORDER.map((setId)=>{const active=activeSet===setId;const complete=setOwned(setId);return <button key={setId} className={active?"is-active":""} onClick={()=>applySet(setId)}><img className="v49-combo-render" src={getCharacterSetAsset(setId)} alt=""/><span>{SETS[setId].shortLabel}</span>{active?<i>✓</i>:<i>{complete?"★":"🔒"}</i>}</button>;})}</div></div></div>
  <div className="v47-learning-strip"><div className="v47-lesson-cta"><span>📖</span><div><strong>Dersler & Öğrenme</strong><small>Yeni bilgiler keşfet, sınavları geç, ödüller kazan.</small></div><button onClick={onOpenLessons}>Derslere Git →</button></div><div className="v47-daily-mini"><b>Önerilen Ders</b><span>Fen Bilimleri · Keşif Görevi</span><i><em style={{width:"60%"}}/></i></div><div className="v47-daily-mini"><b>Günlük Hedef</b><span>1 ders tamamla · 1 soru çöz</span><i><em style={{width:"34%"}}/></i></div></div>
 </section>;
}
